site_name: Picsou's Blog
site_url: https://theocyg.github.io/Blog/
use_directory_urls: true
repo_url: https://github.com/Theocyg/Blog
site_author: Picsou
nav:
  - Home: index.md
  - Hack The Box:
      - Administrator: Hack The Box/Administrator.md
  - Active Directory:
      - Introduction: ActiveDirectory/Introduction.md
      - Kerberos: ActiveDirectory/Kerberos.md
  - Autres: Darknet.md
  - Cheat Sheet: PrivescLinux.md
theme:
  name: simple-blog
  locale: fr
  logo: https://github.com/Theocyg/Blog/raw/main/assets/logo/logo.webp
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
